//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCommerceNiceUrls.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiceUrl_Category : NiceUrl_Url
    {
        public NiceUrl_Category()
        {
            this.ChildCategories = new HashSet<NiceUrl_Category>();
            this.NiceUrl_Products = new HashSet<NiceUrl_Product>();
        }
    
        public int uCommerceCategoryID { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public int CatalogID { get; set; }
    
        public virtual NiceUrl_Catalog NiceUrl_Catalog { get; set; }
        public virtual ICollection<NiceUrl_Category> ChildCategories { get; set; }
        public virtual NiceUrl_Category ParentCategory { get; set; }
        public virtual uCommerce_Category uCommerce_Category { get; set; }
        public virtual ICollection<NiceUrl_Product> NiceUrl_Products { get; set; }
    }
}
