//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCommerceNiceUrls.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiceUrl_Catalog : NiceUrl_Url
    {
        public NiceUrl_Catalog()
        {
            this.NiceUrl_Category = new HashSet<NiceUrl_Category>();
        }
    
        public int uCommerceCatalogID { get; set; }
    
        public virtual uCommerce_ProductCatalog uCommerce_ProductCatalog { get; set; }
        public virtual ICollection<NiceUrl_Category> NiceUrl_Category { get; set; }
    }
}
