//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCommerceNiceUrls.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiceUrl_Url
    {
        public NiceUrl_Url()
        {
            this.NiceUrl_LanguageName = new HashSet<NiceUrl_LanguageName>();
        }
    
        public int ID { get; set; }
    
        public virtual ICollection<NiceUrl_LanguageName> NiceUrl_LanguageName { get; set; }
    }
}
