//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCommerceNiceUrls.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiceUrl_LanguageName
    {
        public int ID { get; set; }
        public string CultureCode { get; set; }
        public string NiceUrl { get; set; }
        public int UrlID { get; set; }
    
        public virtual NiceUrl_Url NiceUrl_Url { get; set; }
    }
}
