//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCommerceNiceUrls.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class uCommerce_Category
    {
        public uCommerce_Category()
        {
            this.NiceUrl_Category = new HashSet<NiceUrl_Category>();
            this.uCommerce_Category1 = new HashSet<uCommerce_Category>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string ImageMediaId { get; set; }
        public bool DisplayOnSite { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public int ProductCatalogId { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public bool Deleted { get; set; }
        public int SortOrder { get; set; }
        public string CreatedBy { get; set; }
        public int DefinitionId { get; set; }
    
        public virtual ICollection<NiceUrl_Category> NiceUrl_Category { get; set; }
        public virtual ICollection<uCommerce_Category> uCommerce_Category1 { get; set; }
        public virtual uCommerce_Category uCommerce_Category2 { get; set; }
        public virtual uCommerce_ProductCatalog uCommerce_ProductCatalog { get; set; }
    }
}
