//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCommerceNiceUrls.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class uCommerce_ProductCatalog
    {
        public uCommerce_ProductCatalog()
        {
            this.NiceUrl_Catalog = new HashSet<NiceUrl_Catalog>();
            this.uCommerce_Category = new HashSet<uCommerce_Category>();
        }
    
        public int ProductCatalogId { get; set; }
        public int ProductCatalogGroupId { get; set; }
        public string Name { get; set; }
        public int PriceGroupId { get; set; }
        public bool ShowPricesIncludingVAT { get; set; }
        public bool IsVirtual { get; set; }
        public bool DisplayOnWebSite { get; set; }
        public bool LimitedAccess { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<NiceUrl_Catalog> NiceUrl_Catalog { get; set; }
        public virtual ICollection<uCommerce_Category> uCommerce_Category { get; set; }
    }
}
